version: "3.8"

services:
  nginx:
    container_name: codend_nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:443"
      - "8081:444"
      - "9011:9011"
    depends_on:
      codendapi:
        condition: service_started
      codendui:
        condition: service_started
      fusionauth:
        condition: service_started
    volumes:
      - "./logs/:/var/log/nginx/:rw"
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      # setup ssl certificates path
      # - "./ssl/codend.key:/etc/ssl/private/codend-selfsigned.key"
      # - "./ssl/codend.crt:/etc/ssl/certs/codend-selfsigned.crt"
    networks:
      - codend_app

  codendui:
    container_name: codend_ui
    image: maksimowiczm/codendui
    build:
      context: ./CodendRemix
      dockerfile: ./Dockerfile
      target: production
    depends_on:
      codendapi:
        condition: service_started
    environment:
      API_SERVER: http://codendapi:5000
    networks:
      - codend_app

  codendapi:
    container_name: codend_api
    image: maksimowiczm/codendapi
    build:
      context: ./Codend
      dockerfile: ./src/api/Codend.Api/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      fusionauth:
        condition: service_started
    environment:
      - "ConnectionStrings:PostgresDatabase=Host=postgres; Database=codendDatabase; Username=${POSTGRES_USER}; Password=${POSTGRES_PASSWORD}"
      - "Fusionauth:ApiKey=${FUSIONAUTH_API_KEY}"
      - "Fusionauth:ApiUrl=http://fusionauth:9011/"
      - "Fusionauth:Issuer=${FUSIONAUTH_ISSUER}"
      - "Fusionauth:ApplicationId=${FUSIONAUTH_APPLICATION_ID}"
      - "Fusionauth:SigningKey=${FUSIONAUTH_SIGNING_KEY}"
      - "Fusionauth:TenantId=${FUSIONAUTH_TENANT_ID}"
      - "ASPNETCORE_URLS=http://+:5000"
    networks:
      - codend_database
      - codend_app

  postgres:
    container_name: codend_postgres
    image: postgres:16.1
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      PGDATA: /var/lib/postgresql/data/
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - codend_database
    volumes:
      - codend_database_data:/var/lib/postgresql/data

  fusionauth:
    container_name: codend_fusionauth
    image: fusionauth/fusionauth-app:1.48.3
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/fusionauth
      DATABASE_ROOT_USERNAME: ${POSTGRES_USER}
      DATABASE_ROOT_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      FUSIONAUTH_APP_MEMORY: ${FUSIONAUTH_APP_MEMORY}
      FUSIONAUTH_APP_RUNTIME_MODE: production
      FUSIONAUTH_APP_URL: http://fusionauth:9011
      SEARCH_TYPE: database
      FUSIONAUTH_APP_KICKSTART_FILE: /usr/local/fusionauth/kickstart/kickstart.json
    networks:
      - codend_database
      - codend_app
    volumes:
      - codend_fusionauth_config:/usr/local/fusionauth/config
      - ./fusionauth.json:/usr/local/fusionauth/kickstart/kickstart.json

networks:
  codend_database:
  codend_app:


volumes:
  codend_database_data:
  codend_fusionauth_config:
